/**
 * Created by eliel on 27/05/2016.
 */

export const SAVE_PLAN = 'SAVE_PLAN';

export const UPDATE_ATTRACTIONS = 'UPDATE_ATTRACTIONS';
export const TOGGLE_ATTRACTION = 'TOGGLE_ATTRACTION';

export const OPTIMIZE_START = "OPTIMIZE_START";
export const OPTIMIZE_SUCCESS = "OPTIMIZE_SUCCESS";
export const OPTIMIZE_FAILURE = "OPTIMIZE_FAILURE";

export const TRIP_ROUTE_START = "TRIP_ROUTE_START";
export const TRIP_ROUTE_SUCCESS = "TRIP_ROUTE_SUCCESS";
export const TRIP_ROUTE_FAILURE = "TRIP_ROUTE_FAILURE";

export const OPTIMIZE_COMPLETE = "OPTIMIZE_COMPLETE";

export const HOTEL = 'HOTEL';
export const LUNCH = 'LUNCH';
export const ATTRACTION = 'ATTRACTION';

export const CHANGE_HOTEL = 'CHANGE_HOTEL';